[2023-12-19T11:31:39.522+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.sense_csv_file scheduled__2023-01-24T00:00:00+00:00 [queued]>
[2023-12-19T11:31:39.662+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.sense_csv_file scheduled__2023-01-24T00:00:00+00:00 [queued]>
[2023-12-19T11:31:39.678+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-19T11:31:40.373+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): sense_csv_file> on 2023-01-24 00:00:00+00:00
[2023-12-19T11:31:40.412+0000] {standard_task_runner.py:57} INFO - Started process 378 to run task
[2023-12-19T11:31:40.436+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'sense_csv_file', 'scheduled__2023-01-24T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/dag0001.py', '--cfg-path', '/tmp/tmpz6njm5d2']
[2023-12-19T11:31:40.564+0000] {standard_task_runner.py:85} INFO - Job 98: Subtask sense_csv_file
[2023-12-19T11:31:42.940+0000] {task_command.py:416} INFO - Running <TaskInstance: my_dag.sense_csv_file scheduled__2023-01-24T00:00:00+00:00 [running]> on host e1038f319166
[2023-12-19T11:31:55.751+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 98 for task sense_csv_file ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 378)
[2023-12-19T11:32:06.299+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
