[2023-12-19T11:25:25.672+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.sense_csv_file scheduled__2023-01-12T00:00:00+00:00 [queued]>
[2023-12-19T11:25:27.382+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.sense_csv_file scheduled__2023-01-12T00:00:00+00:00 [queued]>
[2023-12-19T11:25:27.430+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-12-19T11:25:28.630+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): sense_csv_file> on 2023-01-12 00:00:00+00:00
[2023-12-19T11:25:32.764+0000] {standard_task_runner.py:57} INFO - Started process 245 to run task
[2023-12-19T11:25:33.238+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'sense_csv_file', 'scheduled__2023-01-12T00:00:00+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/dag0001.py', '--cfg-path', '/tmp/tmpxs4dqcsr']
[2023-12-19T11:25:33.311+0000] {standard_task_runner.py:85} INFO - Job 69: Subtask sense_csv_file
[2023-12-19T11:25:59.213+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 69 for task sense_csv_file ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 245)
[2023-12-19T11:28:10.467+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-19T11:28:13.804+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
